INSERT INTO BUILDING(ID, NAME) VALUES(-20, 'Building1');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-10, 'Room1', 1,-20);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-9, 'Room2', 1,-20);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-3, 10, 'ON', -9);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-4, 0, 'OFF', -9);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-5, 10, 'ON', -9);